### ISSUE TITLE
Either use Spring's DI or object creation using new keyword. Not both

### ISSUE THREAD

**Issue by bmorais-feefo** [faria-jr/Feefo-Software-Engineering-technical-assessment#2]
https://github.com/faria-jr/Feefo-Software-Engineering-technical-assessment/blob/1ffe97533a823c3c64cb3e143b1904fb2601f511/src/main/java/com/feefo/technicaltest/application/usecase/impl/NormaliserUseCaseImpl.java#L16

**Comment by faria-jr** [comment]
solved
